'use client';
import { useState, useEffect, useRef } from 'react';
import { ArrowRight, ArrowLeft, Maximize2, ShieldCheck, Database, Workflow, Check, Play, Pause, RotateCcw, LockKeyhole } from 'lucide-react';
const titles=['Introduction','Company','Ownership','Compounding risk','Intervention','One continuum','Value','Path to value'];
const stages=[{name:'Registration',risk:'A small intake error',detail:'Incorrect patient or coverage details enter the claim.',action:'Validate intake and eligibility',product:'AGENTNEX',value:'A cleaner claim starts here.'},{name:'Authorization',risk:'The gap becomes a delay',detail:'Missing authorization adds follow-up and rescheduling.',action:'Verify benefits and prior authorization',product:'AGENTNEX',value:'Resolve upstream gaps before submission.'},{name:'Denial',risk:'One claim becomes more work',detail:'A denial adds investigation, correction and payer calls.',action:'Decode, triage and choose the next action',product:'AUDITNEX',value:'Turn denial reasons into an actionable workstream.'},{name:'Rework',risk:'Time adds to the cost',detail:'Repeated touches consume staff capacity and delay cash.',action:'Correct, resubmit, appeal and follow up',product:'AUDITNEX',value:'Back-office and voice agents move work forward.'},{name:'Recovery',risk:'Unworked claims lose value',detail:'An aging queue leaves recoverable revenue at risk.',action:'Audit underpayments and pursue collections',product:'AUDITNEX',value:'Recover what still slips through.'}];
const notes=[
'Platform overview adapted from source slides 9, 11 and 16.',
'AWS partnership: source deck, slide 15. The 1,000+ white-label practice installation claim comes from the supplied company brief and does not appear in the source deck.',
'“Only on-prem” is positioning supplied in the company brief, not independently verified market exclusivity. The source deck describes deployment in the client’s private cloud, which is distinct from physical on-premises infrastructure. Validate the intended deployment definition before external use. PHI handling statement: source slide 16.',
'Conceptual animation, not a quantitative forecast. The rising curve represents accumulating process burden and revenue exposure, not measured costs or probabilities.',
'Interventions derive from source slides 9–10. The blue path illustrates intended process improvement, not a measured or guaranteed reduction.',
'Workflow and integrations derive from source slides 9–10 and 15. Scope and writeback capabilities depend on the connected systems and implementation.',
'Company-reported impact figures from source slide 11: 40%+ cost reduction and approximately 40%+ denial revenue recovery. These are not independently validated guarantees, and the source does not define the recovery denominator. EBITDA impact must be modeled using each client’s baseline; percentages cannot be added together.',
'Source slide 16 specifies a 2–4 week diagnostic and a 60–90 day pilot. Slide 14 separately describes 4 weeks to pilot readiness; this presentation uses the more detailed phased timeline. Source: Contiinex–ALPS RCM Sales PitchDeck, 8 Sep, plus user-supplied company positioning.'
];
export default function Home(){
const [slide,setSlide]=useState(0),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[notesOpen,setNotesOpen]=useState(false);const touch=useRef<number|null>(null);
const go=(n:number)=>{setSlide(Math.max(0,Math.min(titles.length-1,n)));setPlaying(false);setStep(0);setNotesOpen(false)};
useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('button,a,input,summary'))return;if(e.key==='ArrowRight'||e.key===' '){e.preventDefault();go(slide+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(slide-1)}if(e.key==='Home')go(0);if(e.key==='End')go(titles.length-1)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[slide]);
useEffect(()=>{if(!playing)return;const id=setInterval(()=>setStep(s=>{if(s===4){setPlaying(false);return s}return s+1}),2300);return()=>clearInterval(id)},[playing]);
const journey=(withAI:boolean)=><><div className="section-top"><div><h2>{withAI?<>Every step is a chance<br/>to <em>protect revenue.</em></>:<>A small error.<br/><span className="red">A growing cost.</span></>}</h2></div><div className="play-controls"><button onClick={()=>{if(step===4)setStep(0);setPlaying(!playing)}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause':'Play journey'}</button><button aria-label="Replay journey" onClick={()=>{setStep(0);setPlaying(true)}}><RotateCcw size={16}/></button></div></div><div className="journey"><div className="chart-area"><div className="chart-label">ACCUMULATING WORK + REVENUE AT RISK</div><svg viewBox="0 0 900 240" role="img" aria-label={withAI?'Illustrative rising manual process burden compared with a lower path with Contiinex':'Illustrative process burden increases through five claim stages'}><defs><linearGradient id="redFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#dd133c" stopOpacity=".2"/><stop offset="1" stopColor="#dd133c" stopOpacity="0"/></linearGradient></defs>{[65,125,185].map(y=><path key={y} d={`M30 ${y} H870`} stroke="#e2e4e8" strokeDasharray="3 8"/>)}<path d="M30 207 C140 205 210 190 240 180 S390 156 450 136 S610 91 660 77 S815 30 870 18 L870 228 L30 228Z" fill="url(#redFill)"/><path d="M30 207 C140 205 210 190 240 180 S390 156 450 136 S610 91 660 77 S815 30 870 18" fill="none" stroke="#dd133c" strokeWidth="3" opacity=".25"/><path className="risk-path" style={{strokeDashoffset:1000-(step+1)*200}} pathLength="1000" d="M30 207 C140 205 210 190 240 180 S390 156 450 136 S610 91 660 77 S815 30 870 18" fill="none" stroke="#dd133c" strokeWidth="4" strokeDasharray="1000"/>{withAI&&<path className="risk-path" style={{strokeDashoffset:1000-(step+1)*200}} pathLength="1000" d="M30 207 C220 207 270 203 450 205 S680 202 870 207" stroke="#249cf4" strokeWidth="4" fill="none" strokeDasharray="1000"/>}{[207,180,136,77,18].map((y,i)=><g key={i}><circle cx={30+i*210} cy={y} r={i===step?9:5} fill={i<=step?'#dd133c':'#babdc5'}/>{withAI&&i<=step&&<circle cx={30+i*210} cy="206" r={i===step?8:4} fill="#249cf4"/>}</g>)}</svg><div className="stage-buttons">{stages.map((s,i)=><button key={s.name} className={step===i?'selected':''} onClick={()=>{setStep(i);setPlaying(false)}}><span>0{i+1}</span>{s.name}</button>)}</div><div className="legend"><span><i className="red-dot"/>Manual process</span>{withAI&&<span><i/>With Contiinex</span>}<small>Illustrative, not to scale</small></div></div><div className={'event '+(withAI?'positive':'')} key={`${withAI}-${step}`}><span className="event-label">{withAI?stages[step].product:`RISK BUILDS / 0${step+1}`}</span><h3>{withAI?stages[step].action:stages[step].risk}</h3><p>{withAI?stages[step].value:stages[step].detail}</p>{withAI?<span className="event-end"><Check size={18}/> Prevention + recovery</span>:<span className="event-end red">More touches. Later cash.</span>}</div></div></>;
return <main className="deck" onTouchStart={e=>{touch.current=e.touches[0].clientX}} onTouchEnd={e=>{if(touch.current===null)return;const d=touch.current-e.changedTouches[0].clientX;if(Math.abs(d)>80)go(slide+(d>0?1:-1));touch.current=null}}><header><a className="brand" href="#" onClick={e=>{e.preventDefault();go(0)}}><img src="./brand/contiinex-logo.png" alt="Contiinex" width="200" height="40"/></a><nav aria-label="Presentation chapters">{titles.map((t,i)=><button aria-label={`Slide ${i+1}: ${t}`} aria-current={slide===i?'step':undefined} className={slide===i?'active':''} key={t} onClick={()=>go(i)}><span>{String(i+1).padStart(2,'0')}</span><b>{t}</b></button>)}</nav><button aria-label="Toggle full screen" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else document.documentElement.requestFullscreen?.().catch(()=>{})}}><Maximize2 size={18}/></button></header>
<section key={slide} className={`slide ${slide===0?'cover':slide===1?'credibility':''}`} aria-label={`Slide ${slide+1}: ${titles[slide]}`}>
{slide===0&&<div className="cover-message"><h1>You own the process.<br/><em>We move the margin.</em></h1><p className="intro">Denial prevention and revenue recovery.<br/>Inside your own environment.</p></div>}
{slide===1&&<><h2>Built for your ecosystem.<br/><em>Deployed at scale.</em></h2><div className="proof"><div className="scale"><strong>1,000<span>+</span></strong><p>practices with white-label installations¹</p></div><div className="partner"><b>aws<span>⌣</span></b><div><strong>AWS Partner</strong><p>Procurement through your AWS ecosystem</p></div></div><div className="signal"><i/>Your infrastructure. Your control.</div></div></>}

{slide===2&&<><div className="ownership"><div><h2>The only<br/><em>on-prem</em><br/>solution.</h2><p className="intro">You own the process.<br/>Your team keeps control.</p></div><div className="boundary"><div className="boundary-label"><LockKeyhole size={17}/> YOUR PRIVATE ENVIRONMENT</div><div className="inside"><div className="platform"><img src="./brand/contiinex-logo.png" alt="Contiinex" width="240" height="48"/><span>AGENTIC RCM</span></div><div className="system-row"><div><Database/>Your data</div><div><Workflow/>Your workflows</div><div><ShieldCheck/>Your oversight</div></div></div><p>PHI stays in your infrastructure.</p><span>Contiinex does not store PHI on its own systems.</span></div></div></>}
{slide===3&&journey(false)}{slide===4&&journey(true)}
{slide===5&&<><h2>Prevent upstream.<br/><em>Recover downstream.</em></h2><div className="continuum"><article><div className="product-label">01 / AGENTNEX</div><h3>Fewer preventable denials</h3><div className="workflow-list">{['Scheduling & registration','Eligibility & benefits','Prior authorization'].map(t=><div key={t}><Check size={19}/>{t}</div>)}</div></article><div className="connector"><ArrowRight/></div><article><div className="product-label">02 / AUDITNEX</div><h3>More revenue recovered</h3><div className="workflow-list">{['Denial management & appeals','Underpayment & zero-balance audits','A/R & patient collections'].map(t=><div key={t}><Check size={19}/>{t}</div>)}</div></article></div><div className="integration"><span>BACK OFFICE + VOICE</span><p>Connected to your EHR, practice management, billing and payer systems.</p></div></>}
{slide===6&&<><h2>Two levers.<br/><em>One healthier margin.</em></h2><div className="value-grid"><div><span className="product-label">AGENTNEX / COST LINE</span><strong>40%<small>+</small></strong><h3>Cost reduction</h3><p>Less manual work across upstream operations.</p></div><div><span className="product-label">AUDITNEX / REVENUE LINE</span><strong>~40%<small>+</small></strong><h3>Denial revenue recovery</h3><p>More action on denied and underpaid claims.</p></div><div className="margin"><div className="margin-bars"><i/><i/><i/><i/></div><h3>Higher<br/>EBITDA potential</h3><p>Measured against your own cost and recovery baseline.</p></div></div><p className="fine">Company-reported impact from the source deck. Outcomes vary by client. These percentages are separate measures and are not additive.</p></>}
{slide===7&&<><h2>Your data proves it.<br/><em>Your business scales it.</em></h2><div className="roadmap">{[{n:'01',name:'Diagnostic',time:'2–4 weeks',copy:'Find the opportunity in your own denial and claims data.'},{n:'02',name:'Pilot',time:'60–90 days',copy:'Measure results on 1–2 service lines in your private cloud.'},{n:'03',name:'Scale',time:'Based on pilot results',copy:'Expand prevention and recovery across your claims volume.'}].map(x=><article key={x.n}><span className="phase">{x.n}</span><h3>{x.name}</h3><span className="time">{x.time}</span><p>{x.copy}</p></article>)}</div><div className="closing"><ShieldCheck/><span>One platform. Inside your environment. Accountable to your results.</span></div></>}
</section>
{notesOpen&&<aside className="notes"><strong>Source & claim notes / {titles[slide]}</strong><p>{notes[slide]}</p></aside>}
<footer><button className="source-button" onClick={()=>setNotesOpen(!notesOpen)} aria-expanded={notesOpen}>{notesOpen?'Close notes':'Source notes'} <span>↗</span></button><span className="confidential">CONFIDENTIAL</span><div className="footer-nav"><button aria-label="Previous slide" disabled={slide===0} onClick={()=>go(slide-1)}><ArrowLeft size={18}/></button><span aria-live="polite">{String(slide+1).padStart(2,'0')} <span className="dim">/ {String(titles.length).padStart(2,'0')}</span></span><button aria-label={slide===7?'Restart presentation':'Next slide'} onClick={()=>go(slide===7?0:slide+1)}>{slide===7?<RotateCcw size={18}/>:<ArrowRight size={18}/>}</button></div></footer></main>}
