'use client';
import { useState } from 'react';
import { SlidersHorizontal, ArrowLeft, ShieldCheck } from 'lucide-react';
const trim=(x:string)=>x.replace(/\.?0+$/,'');const money=(v:number)=>{const a=Math.abs(v);const s=a>=1e9?`$${a>=1e10?(a/1e9).toFixed(0):trim((a/1e9).toFixed(2))}B`:a>=1e8?`$${trim((a/1e6).toFixed(1))}M`:a>=1e6?`$${trim((a/1e6).toFixed(2))}M`:`$${Math.round(a/1e3)}K`;return (v<0?'-':'')+s};
const REV_MIN=5e7,REV_SPAN=400;
const revFromSlider=(v:number)=>{const r=REV_MIN*Math.pow(REV_SPAN,v/1000);return r>=1e9?Math.round(r/5e7)*5e7:Math.round(r/1e7)*1e7};
const sliderFromRev=(r:number)=>Math.round(Math.log(Math.min(Math.max(r,REV_MIN),REV_MIN*REV_SPAN)/REV_MIN)/Math.log(REV_SPAN)*1000);
const PRESETS=[1e8,2.5e8,5e8,1e9,2e9];
type A={npsr:number;ebida:number;rcm:number;ebv:number;save:number;price:number;denial:number;recov:number};
const DEFAULTS:A={npsr:1e8,ebida:2,rcm:7,ebv:20,save:32,price:60,denial:15,recov:20};
const SLIDERS:{k:keyof A;l:string;sub:string;min:number;max:number;st:number}[]=[{k:'ebida',l:'EBIDA margin today',sub:'model default 2%',min:0.1,max:10,st:0.1},{k:'rcm',l:'Revenue cycle cost, share of NPSR',sub:'model default 7%',min:3,max:15,st:0.5},{k:'ebv',l:'Eligibility & benefits verification, share of revenue cycle cost',sub:'model default 20%',min:5,max:50,st:1},{k:'save',l:'Contiinex saving on that spend',sub:'model default 32%',min:5,max:70,st:1},{k:'price',l:'Contiinex price, share of that spend',sub:'model default 60%',min:20,max:100,st:5},{k:'denial',l:'Denied dollars, share of NPSR',sub:'model default 15%',min:5,max:25,st:0.5},{k:'recov',l:'Share of denied dollars recovered',sub:'model default 20%',min:1,max:40,st:1}];
const pc=(v:number)=>`${trim(v.toFixed(v<10?2:1))}%`;
export default function PricingPage(){
const [a,setA]=useState<A>(DEFAULTS),[open,setOpen]=useState(false);
const set=(k:keyof A,v:number)=>setA(p=>({...p,[k]:v}));
const npsr=Math.max(a.npsr,1e6);const ebida0=npsr*a.ebida/100,rcmCost=npsr*a.rcm/100,ebv=rcmCost*a.ebv/100,saved=ebv*a.save/100,price=ebv*a.price/100,remain=Math.max(ebv-saved-price,0),over=saved+price>ebv+1,denied=npsr*a.denial/100,recov=denied*a.recov/100,worked=denied-recov,gain=saved+recov,ebida1=ebida0+gain,m1=ebida1/npsr*100,inc=ebida0>0?gain/ebida0:0,mult=ebida0>0?ebida1/ebida0:0,priceShare=price/npsr*100;
const commit=(el:HTMLInputElement)=>{const v=Number(el.value);if(v>0)set('npsr',v*1e6)};
/* proportional flow: sources on the left, destinations on the right */
const W=960,H=560,NX0=250,NX1=700,NW=18,PADY=28,GAP=26;
const left=[{id:'e0',name:'EBIDA today',value:ebida0,cls:'n-ebida'},{id:'ebv',name:'Eligibility & benefits verification spend today',value:ebv,cls:'n-src'},{id:'den',name:'Denied dollars',value:denied,cls:'n-src'}];
const right=[{id:'e1',name:'EBIDA with Contiinex',value:ebida1,cls:'n-ebida'},{id:'price',name:'Paid to Contiinex',value:price,cls:'n-price'},{id:'remain',name:'Verification spend remaining',value:remain,cls:'n-grey'},{id:'worked',name:'Denials worked as today',value:worked,cls:'n-grey'}];
const links=[{from:'e0',to:'e1',value:ebida0,cls:'l-ebida',label:'',t:.5},{from:'ebv',to:'e1',value:saved,cls:'l-ebida',label:'Cost saved',t:.5},{from:'ebv',to:'price',value:price,cls:'l-price',label:'Contiinex price',t:.24},{from:'ebv',to:'remain',value:remain,cls:'l-grey',label:'',t:.5},{from:'den',to:'e1',value:recov,cls:'l-ebida',label:'Recovered',t:.78},{from:'den',to:'worked',value:worked,cls:'l-grey',label:'',t:.5}];
const total=Math.max(left.reduce((s,n)=>s+n.value,0),1);const k=(H-2*PADY-GAP*3)/total;const hOf=(v:number)=>Math.max(v*k,2);
const pos:Record<string,{y:number;h:number;x:number}>={};let yy=PADY;left.forEach(n=>{pos[n.id]={y:yy,h:hOf(n.value),x:NX0};yy+=hOf(n.value)+GAP});yy=PADY;right.forEach(n=>{pos[n.id]={y:yy,h:hOf(n.value),x:NX1};yy+=hOf(n.value)+GAP});
const outOff:Record<string,number>={},inOff:Record<string,number>={};
const bands=links.map(l=>{const h=Math.max(l.value*k,1.5);const s=pos[l.from],t=pos[l.to];const y0=s.y+(outOff[l.from]||0);outOff[l.from]=(outOff[l.from]||0)+h;const y1=t.y+(inOff[l.to]||0);inOff[l.to]=(inOff[l.to]||0)+h;const x0=s.x+NW,x1=t.x,mx=(x0+x1)/2;const u=l.t,c0=y0+h/2,c1=y1+h/2;const lx=x0*Math.pow(1-u,3)+3*mx*u*Math.pow(1-u,2)+3*mx*u*u*(1-u)+x1*Math.pow(u,3);const ly=c0*Math.pow(1-u,2)*(1+2*u)+c1*u*u*(3-2*u);return {...l,h,d:`M${x0} ${y0} C${mx} ${y0} ${mx} ${y1} ${x1} ${y1} L${x1} ${y1+h} C${mx} ${y1+h} ${mx} ${y0+h} ${x0} ${y0+h} Z`,lx,ly}});
const base=ebida0,max=ebida1*1.18||1;
const bars=[{label:'EBIDA today',sub:`${pc(a.ebida)} of NPSR`,from:0,to:base,cls:'base',val:money(base)},{label:'Cost saved',sub:'eligibility & benefits verification',from:base,to:base+saved,cls:'add',val:'+'+money(saved)},{label:'Recovered',sub:`${pc(a.recov)} of denied dollars`,from:base+saved,to:ebida1,cls:'add',val:'+'+money(recov)},{label:'With Contiinex',sub:`${pc(m1)} of NPSR`,from:0,to:ebida1,cls:'total',val:money(ebida1)}];
return <main className="deck pricing-page"><header><a className="brand" href="./index.html"><img src="./brand/contiinex-logo.png" alt="Contiinex" width="200" height="40"/></a><a className="back-link" href="./index.html"><ArrowLeft size={16}/> Presentation</a></header>
<section className="slide">
<p className="eyebrow">PRICING / ILLUSTRATIVE MODEL</p><h1>Simple, predictable pricing.<br/><em>Aligned to outcomes.</em></h1><p className="intro">Contiinex is priced as a share of what you already spend on eligibility and benefits verification. The saving on that spend, and the denied dollars recovered, flow straight to EBIDA.</p>
<div className="controls"><div className="rev-block"><label className="rev-label" htmlFor="npsr">NET PATIENT SERVICE REVENUE, PER YEAR</label><div className="rev-value">{money(npsr)}</div><input id="npsr" type="range" min="0" max="1000" value={sliderFromRev(npsr)} onChange={e=>set('npsr',revFromSlider(+e.target.value))}/><div className="presets"><span>Try</span>{PRESETS.map(v=><button key={v} className={npsr===v?'selected':''} onClick={()=>set('npsr',v)}>{money(v)}</button>)}<label>or $M <input key={npsr} type="number" min="1" step="50" defaultValue={Math.round(npsr/1e6)} onBlur={e=>commit(e.target)} onKeyDown={e=>{if(e.key==='Enter')commit(e.currentTarget)}} aria-label="Net patient service revenue in millions of dollars"/></label></div></div><div className="basis"><p>On <b>{money(npsr)}</b>, the revenue cycle costs <b>{money(rcmCost)}</b> ({pc(a.rcm)}), of which <b>{money(ebv)}</b> ({pc(a.ebv)}) goes to eligibility and benefits verification. <b>{money(denied)}</b> ({pc(a.denial)}) of claims is denied each year.</p><button className="settings-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}><SlidersHorizontal size={15}/>{open?'Hide assumptions':'Adjust assumptions'}</button></div></div>
{open&&<div className="assumptions"><div className="assume-head">ASSUMPTIONS <small>model defaults shown; every one is replaced by your own data in the diagnostic</small></div><div className="assume-grid">{SLIDERS.map(s=><label key={s.k}><span>{s.l}<em>{s.sub}</em></span><input type="range" min={s.min} max={s.max} step={s.st} value={a[s.k]} onChange={e=>set(s.k,+e.target.value)}/><b>{a[s.k]}%</b></label>)}</div>{over&&<p className="warn">Saving and price together exceed the verification spend; the remaining share is shown as zero.</p>}</div>}
<div className="derive"><div className="chart-label">WHERE THE DOLLARS COME FROM</div>{[{name:'Net patient service revenue',total:npsr,part:rcmCost,share:a.rcm,label:'Revenue cycle cost'},{name:'Revenue cycle cost',total:rcmCost,part:ebv,share:a.ebv,label:'Eligibility & benefits verification'},{name:'Net patient service revenue',total:npsr,part:denied,share:a.denial,label:'Denied dollars'}].map((r,i)=><div key={i} className="derive-row"><span className="derive-name">{r.name}<b>{money(r.total)}</b></span><div className="derive-bar"><i style={{width:`${Math.min(r.share,100)}%`}}/></div><span className="derive-part">{r.label} · {pc(r.share)} · <b>{money(r.part)}</b></span></div>)}</div>
<div className="flow-wrap"><div className="chart-label">COST FLOW, PER YEAR · WHAT YOU SPEND, WHAT YOU PAY, WHAT YOU KEEP</div><svg className="flow" viewBox={`0 0 ${W} ${H}`} role="img" aria-label={`Of ${money(ebv)} spent on eligibility and benefits verification today, ${money(price)} is paid to Contiinex, ${money(saved)} is saved and ${money(remain)} remains. Of ${money(denied)} denied, ${money(recov)} is recovered. EBIDA rises from ${money(ebida0)} to ${money(ebida1)}.`}>{bands.map(b=><path key={b.from+b.to} className={'band '+b.cls} d={b.d}/>)}{left.map(n=><g key={n.id}><rect className={'node '+n.cls} x={pos[n.id].x} y={pos[n.id].y} width={NW} height={pos[n.id].h} rx="3"/><text className="nlabel" x={pos[n.id].x-12} y={pos[n.id].y+Math.min(pos[n.id].h/2,26)} textAnchor="end"><tspan className="nname">{n.name}</tspan><tspan className="nval" x={pos[n.id].x-12} dy="18">{money(n.value)}</tspan></text></g>)}{right.map(n=><g key={n.id}><rect className={'node '+n.cls} x={pos[n.id].x} y={pos[n.id].y} width={NW} height={pos[n.id].h} rx="3"/><text className="nlabel" x={pos[n.id].x+NW+12} y={pos[n.id].y+Math.min(pos[n.id].h/2,26)} textAnchor="start"><tspan className="nname">{n.name}</tspan><tspan className="nval" x={pos[n.id].x+NW+12} dy="18">{money(n.value)}</tspan></text></g>)}{bands.filter(b=>b.label).map(b=><text key={'l'+b.from+b.to} className="blabel" x={b.lx} y={b.ly+4} textAnchor="middle">{b.label} · {money(b.value)}</text>)}</svg><div className="flow-key"><span><i className="k-src"/>Today's spend and denials</span><span><i className="k-price"/>Paid to Contiinex</span><span><i className="k-ebida"/>Flows to EBIDA</span><span><i className="k-grey"/>Unchanged</span></div></div>
<div className="outcome"><div className="tiles"><div><span className="product-label">YOU PAY</span><strong>{money(price)}</strong><p>a year to Contiinex. {pc(a.price)} of your eligibility and benefits verification spend, {priceShare.toFixed(2)}% of NPSR.</p></div><div><span className="product-label">YOU KEEP</span><strong>{money(gain)}</strong><p>a year added to EBIDA: {money(saved)} of cost saved plus {money(recov)} of denied dollars recovered.</p></div><div><span className="product-label">EBIDA</span><strong>{pc(a.ebida)} <span className="arr">→</span> {pc(m1)}</strong><p>of NPSR. Up {trim((inc*100).toFixed(1))}%, or {mult.toFixed(1)}x, on {money(ebida0)} today.</p></div></div>
<div className="bridge-wrap"><div className="chart-label">EBIDA BRIDGE, PER YEAR</div><div className="bridge" role="img" aria-label={`EBIDA today ${money(base)}, plus ${money(saved)} cost saved, plus ${money(recov)} recovered, equals ${money(ebida1)} with Contiinex`}>{bars.map(b=><div key={b.label} className="col"><div className="area"><div className={'bar '+b.cls} style={{bottom:`${b.from/max*100}%`,height:`${Math.max(b.to-b.from,0)/max*100}%`}}><span>{b.val}</span></div></div><div className="col-label"><strong>{b.label}</strong><small>{b.sub}</small></div></div>)}</div></div></div>
<div className="closing"><ShieldCheck/><span>Priced on your own spend, so the saving is locked in before the first denial is prevented. Next step: a 2 to 4 week diagnostic on your own claims data.</span></div>
<p className="fine">Illustrative model, not a quote or a forecast. Source: Contiinex–ALPS pricing model, ALPS tab, updated 16 Sep 2026: EBIDA 2% of NPSR; revenue cycle cost 7% of NPSR; eligibility and benefits verification 20% of that; Contiinex saving 32% of that spend and Contiinex price 60% of it; denied dollars 15% of NPSR; 20% of denied dollars recovered. The effective EBIDA increase is the gain over today’s EBIDA. EBIDA is earnings before interest, depreciation and amortization, the usual nonprofit hospital measure. Implementation and infrastructure are not in the model.</p>
</section>
<footer><span className="confidential">CONFIDENTIAL</span></footer></main>}
